name: leet_game
description: "LeetGame - Gamify DSA learning by thinking like a computer"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  fl_chart: ^0.70.2
  confetti: ^0.8.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
